// packages/rizzo-css/scaffold/react/base/src/App.tsx
export default function App() {
  return (
    <>
      <a href="#main-content" className="skip-link">Skip to main content</a>
      <main id="main-content" className="container">
        <h1>Hello, Rizzo CSS</h1>
        <p>Edit <code>src/App.tsx</code> and add components. Run <code>npx rizzo-css add Button</code> to add Rizzo components.</p>
        <p>
          <a href="https://rizzo-css.vercel.app" className="btn btn-primary">Docs — rizzo-css.vercel.app</a>
        </p>
      </main>
    </>
  );
}

// packages/rizzo-css/scaffold/vue/base/src/App.vue
<template>
  <a href="#main-content" class="skip-link">Skip to main content</a>
  <main id="main-content" class="container">
    <h1>Hello, Rizzo CSS</h1>
    <p>Edit <code>src/App.vue</code> and add components. Run <code>npx rizzo-css add Button</code> to add Rizzo components.</p>
    <p>
      <a href="https://rizzo-css.vercel.app" class="btn btn-primary">Docs — rizzo-css.vercel.app</a>
    </p>
  </main>
</template>

<script setup lang="ts">
</script>

<style scoped>
</style>
