// packages/rizzo-css/scaffold/svelte-app/src/lib/rizzo/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  type Variant = 'default' | 'primary' | 'success' | 'warning' | 'error' | 'info' | 'outline';
  interface Props {
    variant?: Variant;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    class?: string;
    children?: Snippet;
  }
  let {
    variant = 'default',
    disabled = false,
    type = 'button',
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  const variantClass = $derived(variant === 'default' ? '' : `btn-${variant}`);
  const classes = $derived(['btn', variantClass, className].filter(Boolean).join(' '));
</script>

<button {type} {disabled} class={classes} {...rest}>
  {@render children?.()}
</button>

// packages/rizzo-css/scaffold/react/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';

export type ButtonVariant =
  | 'default'
  | 'primary'
  | 'success'
  | 'warning'
  | 'error'
  | 'info'
  | 'outline';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  children?: ReactNode;
  className?: string;
}

/**
 * Button component using Rizzo CSS BEM classes (btn, btn-primary, etc.).
 * Same API and markup as Astro/Svelte Button for design system parity.
 */
export function Button({
  variant = 'default',
  type = 'button',
  disabled = false,
  className = '',
  children,
  ...rest
}: ButtonProps) {
  const variantClass = variant === 'default' ? '' : `btn-${variant}`;
  const classes = ['btn', variantClass, className].filter(Boolean).join(' ');

  return (
    <button type={type} disabled={disabled} className={classes} {...rest}>
      {children}
    </button>
  );
}

export default Button;
