// packages/rizzo-css/scaffold/vue/Checkbox.vue
<script setup lang="ts">
defineProps<{
  id?: string;
  name?: string;
  value?: string;
  modelValue?: boolean;
  required?: boolean;
  disabled?: boolean;
  class?: string;
  ariaDescribedby?: string;
  ariaLabel?: string;
}>();

const emit = defineEmits<{ (e: 'update:modelValue', value: boolean): void }>();
</script>

<template>
  <input
    type="checkbox"
    :id="id"
    :name="name"
    :value="value"
    :checked="modelValue"
    :required="required"
    :disabled="disabled"
    :class="$props.class"
    :aria-describedby="ariaDescribedby"
    :aria-label="ariaLabel"
    @change="emit('update:modelValue', ($event.target as HTMLInputElement).checked)"
  />
</template>

// packages/rizzo-css/scaffold/react/Checkbox.tsx
import type { InputHTMLAttributes } from 'react';

export interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> {
  ariaDescribedby?: string;
  ariaLabel?: string;
  className?: string;
}

export function Checkbox({
  id,
  name,
  value,
  checked = false,
  required = false,
  disabled = false,
  className = '',
  ariaDescribedby,
  ariaLabel,
  onChange,
  ...rest
}: CheckboxProps) {
  return (
    <input
      type="checkbox"
      id={id}
      name={name}
      value={value}
      checked={checked}
      required={required}
      disabled={disabled}
      className={className}
      aria-describedby={ariaDescribedby}
      aria-label={ariaLabel}
      onChange={onChange}
      {...rest}
    />
  );
}

export default Checkbox;
