// packages/rizzo-css/scaffold/svelte/Checkbox.svelte
<script lang="ts">
  interface Props {
    id?: string;
    name?: string;
    value?: string;
    checked?: boolean;
    required?: boolean;
    disabled?: boolean;
    class?: string;
    ariaDescribedby?: string;
    ariaLabel?: string;
  }
  let {
    id,
    name,
    value,
    checked = $bindable(false),
    required = false,
    disabled = false,
    class: className = '',
    ariaDescribedby,
    ariaLabel,
  }: Props = $props();
</script>

<input
  type="checkbox"
  {id}
  {name}
  {value}
  bind:checked
  {required}
  {disabled}
  class={className}
  aria-describedby={ariaDescribedby}
  aria-label={ariaLabel}
/>

// packages/rizzo-css/scaffold/react/Checkbox.tsx
import type { InputHTMLAttributes } from 'react';

export interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> {
  ariaDescribedby?: string;
  ariaLabel?: string;
  className?: string;
}

export function Checkbox({
  id,
  name,
  value,
  checked = false,
  required = false,
  disabled = false,
  className = '',
  ariaDescribedby,
  ariaLabel,
  onChange,
  ...rest
}: CheckboxProps) {
  return (
    <input
      type="checkbox"
      id={id}
      name={name}
      value={value}
      checked={checked}
      required={required}
      disabled={disabled}
      className={className}
      aria-describedby={ariaDescribedby}
      aria-label={ariaLabel}
      onChange={onChange}
      {...rest}
    />
  );
}

export default Checkbox;
