// packages/rizzo-css/scaffold/svelte/Empty.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    title?: string;
    description?: string;
    class?: string;
    icon?: Snippet;
    action?: Snippet;
  }

  let {
    title = 'No results',
    description,
    class: className = '',
    icon,
    action,
  }: Props = $props();
</script>

<div class="empty {className}">
  {#if icon}
    <div class="empty__icon">
      {@render icon()}
    </div>
  {/if}
  <h3 class="empty__title">{title}</h3>
  {#if description}
    <p class="empty__description">{description}</p>
  {/if}
  {#if action}
    <div class="empty__action">
      {@render action()}
    </div>
  {/if}
</div>

// packages/rizzo-css/scaffold/react/Empty.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface EmptyProps extends HTMLAttributes<HTMLDivElement> {
  title?: string;
  description?: string;
  icon?: ReactNode;
  action?: ReactNode;
  className?: string;
}

export function Empty({
  title = 'No results',
  description,
  icon,
  action,
  className = '',
  ...rest
}: EmptyProps) {
  return (
    <div className={`empty ${className}`.trim()} {...rest}>
      {icon && <div className="empty__icon">{icon}</div>}
      <h3 className="empty__title">{title}</h3>
      {description && <p className="empty__description">{description}</p>}
      {action && <div className="empty__action">{action}</div>}
    </div>
  );
}

export default Empty;
