// packages/rizzo-css/scaffold/svelte-app/src/lib/rizzo/FormGroup.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    label?: string;
    labelFor?: string;
    required?: boolean;
    help?: string;
    error?: string;
    success?: string;
    class?: string;
    children?: Snippet;
  }
  let {
    label,
    labelFor,
    required = false,
    help,
    error,
    success,
    class: className = '',
    children,
  }: Props = $props();

  const errorId = $derived(labelFor && error ? `${labelFor}-error` : undefined);
  const helpId = $derived(labelFor && help ? `${labelFor}-help` : undefined);
</script>

<div class="form-group {className}">
  {#if label}
    {#if labelFor}
      <label for={labelFor} class="form-group__label {required ? 'required' : ''}">
        {label}
      </label>
    {:else}
      <span class="form-group__label {required ? 'required' : ''}">
        {label}
      </span>
    {/if}
  {/if}
  {@render children?.()}
  {#if help}
    <span id={helpId} class="form-group__help">{help}</span>
  {/if}
  {#if error}
    <span id={errorId} class="form-error" role="alert">{error}</span>
  {/if}
  {#if success}
    <span class="form-success" role="status">{success}</span>
  {/if}
</div>

// packages/rizzo-css/scaffold/react/FormGroup.tsx
import type { ReactNode } from 'react';

export interface FormGroupProps {
  label?: string;
  labelFor?: string;
  required?: boolean;
  help?: string;
  error?: string;
  success?: string;
  className?: string;
  children?: ReactNode;
}

export function FormGroup({
  label,
  labelFor,
  required = false,
  help,
  error,
  success,
  className = '',
  children,
}: FormGroupProps) {
  const errorId = labelFor && error ? `${labelFor}-error` : undefined;
  const helpId = labelFor && help ? `${labelFor}-help` : undefined;

  return (
    <div className={`form-group ${className}`.trim()}>
      {label &&
        (labelFor ? (
          <label htmlFor={labelFor} className={`form-group__label ${required ? 'required' : ''}`.trim()}>
            {label}
          </label>
        ) : (
          <span className={`form-group__label ${required ? 'required' : ''}`.trim()}>{label}</span>
        ))}
      {children}
      {help && (
        <span id={helpId} className="form-group__help">
          {help}
        </span>
      )}
      {error && (
        <span id={errorId} className="form-error" role="alert">
          {error}
        </span>
      )}
      {success && (
        <span className="form-success" role="status">
          {success}
        </span>
      )}
    </div>
  );
}

export default FormGroup;
