// packages/rizzo-css/scaffold/vue/Input.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    type?: string;
    id?: string;
    name?: string;
    modelValue?: string;
    placeholder?: string;
    required?: boolean;
    disabled?: boolean;
    readonly?: boolean;
    size?: 'sm' | 'md' | 'lg';
    error?: boolean;
    success?: boolean;
    class?: string;
    ariaDescribedby?: string;
    ariaInvalid?: boolean | 'true' | 'false';
  }>(),
  {
    type: 'text',
    modelValue: '',
    required: false,
    disabled: false,
    readonly: false,
    size: 'md',
    error: false,
    success: false,
    class: '',
  }
);

const emit = defineEmits<{ (e: 'update:modelValue', value: string): void }>();

const sizeClass = props.size !== 'md' ? `form-input--${props.size}` : '';
const errorClass = props.error ? 'form-input--error' : '';
const successClass = props.success ? 'form-input--success' : '';
const classes = ['form-input', sizeClass, errorClass, successClass, props.class]
  .filter(Boolean)
  .join(' ')
  .trim();
const invalid = props.error || props.ariaInvalid === true || props.ariaInvalid === 'true';
</script>

<template>
  <input
    :type="type"
    :id="id"
    :name="name"
    :value="modelValue"
    :placeholder="placeholder"
    :required="required"
    :disabled="disabled"
    :readonly="readonly"
    :class="classes"
    :aria-invalid="invalid ? 'true' : 'false'"
    :aria-describedby="ariaDescribedby"
    @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
  />
</template>

// packages/rizzo-css/scaffold/react/Input.tsx
import type { InputHTMLAttributes } from 'react';

export type InputSize = 'sm' | 'md' | 'lg';

export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> {
  size?: InputSize;
  error?: boolean;
  success?: boolean;
  ariaDescribedby?: string;
  ariaInvalid?: boolean | 'true' | 'false';
  onValueChange?: (value: string) => void;
  className?: string;
}

export function Input({
  type = 'text',
  id,
  name,
  value = '',
  placeholder,
  required = false,
  disabled = false,
  readOnly = false,
  autoComplete,
  size = 'md',
  error = false,
  success = false,
  className = '',
  ariaDescribedby,
  ariaInvalid,
  onChange,
  onValueChange,
  ...rest
}: InputProps) {
  const sizeClass = size !== 'md' ? `form-input--${size}` : '';
  const errorClass = error ? 'form-input--error' : '';
  const successClass = success ? 'form-input--success' : '';
  const classes = ['form-input', sizeClass, errorClass, successClass, className]
    .filter(Boolean)
    .join(' ')
    .trim();
  const invalid = error || ariaInvalid === true || ariaInvalid === 'true';

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onChange?.(e);
    onValueChange?.(e.target.value);
  };

  return (
    <input
      type={type}
      id={id}
      name={name}
      value={value}
      placeholder={placeholder}
      required={required}
      disabled={disabled}
      readOnly={readOnly}
      autoComplete={autoComplete}
      className={classes}
      aria-invalid={invalid ? 'true' : 'false'}
      aria-describedby={ariaDescribedby}
      onChange={handleChange}
      {...rest}
    />
  );
}

export default Input;
