// packages/rizzo-css/scaffold/svelte/ResizableHandle.svelte
<script lang="ts">
  interface Props {
    withHandle?: boolean;
    class?: string;
  }

  let { withHandle = false, class: className = '' }: Props = $props();
</script>

<div
  class="resizable__handle {withHandle ? 'resizable__handle--with-handle' : ''} {className}"
  data-resizable-handle
></div>

// packages/rizzo-css/scaffold/react/ResizableHandle.tsx
import type { HTMLAttributes } from 'react';

export interface ResizableHandleProps extends HTMLAttributes<HTMLDivElement> {
  withHandle?: boolean;
  className?: string;
}

export function ResizableHandle({
  withHandle = false,
  className = '',
  ...rest
}: ResizableHandleProps) {
  const classes = [
    'resizable__handle',
    withHandle ? 'resizable__handle--with-handle' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ')
    .trim();
  return <div className={classes} data-resizable-handle {...rest} />;
}

export default ResizableHandle;
