// packages/rizzo-css/scaffold/svelte/ScrollArea.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    orientation?: 'vertical' | 'horizontal';
    class?: string;
    children?: Snippet;
  }

  let { orientation = 'vertical', class: className = '', children }: Props = $props();
  const horizontal = $derived(orientation === 'horizontal');
</script>

<div class="scroll-area {horizontal ? 'scroll-area--horizontal' : ''} {className}">
  <div class="scroll-area__viewport" tabindex="0">
    {@render children?.()}
  </div>
</div>

// packages/rizzo-css/scaffold/react/ScrollArea.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface ScrollAreaProps extends HTMLAttributes<HTMLDivElement> {
  orientation?: 'vertical' | 'horizontal';
  children?: ReactNode;
  className?: string;
}

export function ScrollArea({
  orientation = 'vertical',
  className = '',
  children,
  ...rest
}: ScrollAreaProps) {
  const horizontal = orientation === 'horizontal';
  const classes = ['scroll-area', horizontal ? 'scroll-area--horizontal' : '', className]
    .filter(Boolean)
    .join(' ')
    .trim();
  return (
    <div className={classes} {...rest}>
      <div className="scroll-area__viewport" tabIndex={0}>
        {children}
      </div>
    </div>
  );
}

export default ScrollArea;
