// src/components/svelte/Separator.svelte
<script lang="ts">
  interface Props {
    orientation?: 'horizontal' | 'vertical';
    class?: string;
  }

  let { orientation = 'horizontal', class: className = '' }: Props = $props();
</script>

<div
  class="separator separator--{orientation} {className}"
  role="separator"
  aria-orientation={orientation}
></div>

// packages/rizzo-css/scaffold/react/Separator.tsx
import type { HTMLAttributes } from 'react';

export interface SeparatorProps extends HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical';
  decorative?: boolean;
  className?: string;
}

export function Separator({
  orientation = 'horizontal',
  decorative = true,
  className = '',
  ...rest
}: SeparatorProps) {
  const classes = [
    'separator',
    `separator--${orientation}`,
    className,
  ]
    .filter(Boolean)
    .join(' ')
    .trim();
  return (
    <div
      className={classes}
      role={decorative ? 'none' : 'separator'}
      aria-orientation={decorative ? undefined : orientation}
      {...rest}
    />
  );
}

export default Separator;
