// packages/rizzo-css/scaffold/react/Footer.tsx
import type { HTMLAttributes } from 'react';

export interface FooterLink {
  href: string;
  label: string;
}

export interface FooterProps extends HTMLAttributes<HTMLElement> {
  siteName?: string;
  year?: number;
  links?: FooterLink[];
  className?: string;
}

export function Footer({
  siteName = '',
  year = new Date().getFullYear(),
  links = [],
  className = '',
  ...rest
}: FooterProps) {
  const classes = ['footer', className].filter(Boolean).join(' ').trim();
  return (
    <footer className={classes} {...rest}>
      <div className="footer__container">
        <div className="footer__inner">
          <p className="footer__copyright">
            {siteName && (
              <>
                <span className="footer__site-name">{siteName}</span>
                {' · '}
              </>
            )}
            <span className="footer__year">© {year}</span>
          </p>
          {links && links.length > 0 && (
            <nav className="footer__nav" aria-label="Footer">
              <ul className="footer__links">
                {links.map((link, i) => (
                  <li key={i} className="footer__link-item">
                    <a className="footer__link" href={link.href}>
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          )}
        </div>
      </div>
    </footer>
  );
}

export default Footer;

// src/components/svelte/Footer.svelte
<script lang="ts">
  export interface FooterLink {
    href: string;
    label: string;
  }

  interface Props {
    /** Site or product name shown in copyright */
    siteName?: string;
    /** Copyright year (default: current year) */
    year?: number;
    /** Optional list of footer links */
    links?: FooterLink[];
    class?: string;
  }
  let {
    siteName = '',
    year = new Date().getFullYear(),
    links = [],
    class: className = '',
  }: Props = $props();

  const classes = $derived(['footer', className].filter(Boolean).join(' ').trim());
</script>

<footer class={classes}>
  <div class="footer__container">
    <div class="footer__inner">
      <p class="footer__copyright">
        {#if siteName}
          <span class="footer__site-name">{siteName}</span>
          {' · '}
        {/if}
        <span class="footer__year">© {year}</span>
      </p>
      {#if links && links.length > 0}
        <nav class="footer__nav" aria-label="Footer">
          <ul class="footer__links">
            {#each links as link}
              <li class="footer__link-item">
                <a class="footer__link" href={link.href}>{link.label}</a>
              </li>
            {/each}
          </ul>
        </nav>
      {/if}
    </div>
  </div>
</footer>
