// packages/rizzo-css/scaffold/vue/Label.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    for?: string;
    required?: boolean;
    class?: string;
  }>(),
  { required: false, class: '' }
);
</script>

<template>
  <label
    v-if="$props.for"
    :for="$props.for"
    :class="['label', required ? 'label--required' : '', $props.class].filter(Boolean).join(' ')"
  >
    <slot />
  </label>
  <span v-else :class="['label', required ? 'label--required' : '', $props.class].filter(Boolean).join(' ')">
    <slot />
  </span>
</template>

// src/components/svelte/Label.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    for?: string;
    required?: boolean;
    class?: string;
    children?: Snippet;
  }

  let { for: forId, required = false, class: className = '', children }: Props = $props();
  const classes = $derived(['label', required ? 'label--required' : '', className].filter(Boolean).join(' '));
</script>

{#if forId}
  <label for={forId} class={classes}>{@render children?.()}</label>
{:else}
  <span class={classes}>{@render children?.()}</span>
{/if}
