// src/components/react/Navbar.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { useState, useEffect } from 'react';

export interface NavbarLink {
  href: string;
  label: string;
}

export interface NavbarProps extends HTMLAttributes<HTMLElement> {
  siteName?: string;
  logo?: string;
  /** Desktop: slot for Search + Settings. */
  children?: ReactNode;
  /** Mobile menu links (same as Astro/Svelte/Vue/Vanilla demos). */
  menuLinks?: NavbarLink[];
}

const DEFAULT_MENU_LINKS: NavbarLink[] = [
  { href: '/docs', label: 'Docs' },
  { href: '/docs/components', label: 'Components' },
  { href: '/blocks', label: 'Blocks' },
  { href: '/themes', label: 'Themes' },
];

export function Navbar({
  siteName = 'Site',
  logo,
  children,
  menuLinks = DEFAULT_MENU_LINKS,
  className = '',
  ...rest
}: NavbarProps) {
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    if (!menuOpen) return;
    const onEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setMenuOpen(false);
    };
    const onClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (target && !(target as Element).closest?.('.navbar')) setMenuOpen(false);
    };
    document.addEventListener('keydown', onEscape);
    const t = setTimeout(() => document.addEventListener('click', onClick), 0);
    return () => {
      document.removeEventListener('keydown', onEscape);
      document.removeEventListener('click', onClick);
      clearTimeout(t);
    };
  }, [menuOpen]);

  return (
    <nav className={`navbar ${menuOpen ? 'navbar--menu-open' : ''} ${className}`.trim()} role="navigation" aria-label="Main navigation" {...rest}>
      <div className="navbar__container">
        <div className="navbar__brand">
          <a href="/" className="navbar__brand-link">
            {logo ? (
              <img src={logo} alt="" className="navbar__logo" />
            ) : (
              <span className="navbar__logo" aria-hidden="true">◎</span>
            )}
            {siteName}
          </a>
        </div>
        {children && <div className="navbar__actions-desktop">{children}</div>}
        <button
          type="button"
          className="navbar__toggle"
          aria-label="Toggle menu"
          aria-expanded={menuOpen}
          aria-controls="navbar-menu"
          onClick={() => setMenuOpen((o) => !o)}
        >
          <span className="navbar__toggle-icon" aria-hidden="true">
            <span /><span /><span />
          </span>
        </button>
        <div
          className={`navbar__menu ${menuOpen ? 'navbar__menu--open' : ''}`}
          id="navbar-menu"
          role="navigation"
          aria-label="Mobile menu"
          aria-hidden={!menuOpen}
        >
          {menuLinks.map((link) => (
            <div key={link.href} className="navbar__item">
              <a
                href={link.href}
                className="navbar__link"
                tabIndex={menuOpen ? 0 : -1}
              >
                {link.label}
              </a>
            </div>
          ))}
        </div>
      </div>
    </nav>
  );
}

export default Navbar;

// src/components/svelte/Navbar.svelte
<script lang="ts">
  import Cat from './icons/Cat.svelte';
  import Gear from './icons/Gear.svelte';
  import Search from './Search.svelte';

  interface Props {
    siteName?: string;
    logo?: string;
  }
  let { siteName = 'Site', logo }: Props = $props();
  let menuOpen = $state(false);

  const menuLinks = [
    { href: '/docs', label: 'Docs' },
    { href: '/docs/components', label: 'Components' },
    { href: '/blocks', label: 'Blocks' },
    { href: '/themes', label: 'Themes' },
  ];

  // Click outside and Escape to close mobile menu
  $effect(() => {
    if (!menuOpen) return;
    const onEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') menuOpen = false;
    };
    const onClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (target && !(target as Element).closest?.('.navbar')) menuOpen = false;
    };
    document.addEventListener('keydown', onEscape);
    const t = setTimeout(() => document.addEventListener('click', onClick), 0);
    return () => {
      document.removeEventListener('keydown', onEscape);
      document.removeEventListener('click', onClick);
      clearTimeout(t);
    };
  });
</script>

<nav class="navbar" role="navigation" aria-label="Main navigation">
  <div class="navbar__container">
    <div class="navbar__brand">
      <a href="/" class="navbar__brand-link">
        {#if logo}
          <img src={logo} alt="" class="navbar__logo" />
        {:else}
          <Cat width={32} height={32} class="navbar__logo" aria-hidden="true" />
        {/if}
        {siteName}
      </a>
    </div>
    <div class="navbar__actions-desktop">
      <Search id="search-navbar" />
      <button type="button" class="navbar__settings-btn" aria-label="Open settings" onclick={() => window.openSettings?.()}>
        <Gear width={20} height={20} class="navbar__settings-icon" />
        <span class="navbar__settings-label">Settings</span>
      </button>
    </div>
    <button
      type="button"
      class="navbar__toggle"
      aria-label="Toggle menu"
      aria-expanded={menuOpen}
      onclick={() => (menuOpen = !menuOpen)}
    >
      <span class="navbar__toggle-icon" aria-hidden="true"><span></span><span></span><span></span></span>
    </button>
    <div class="navbar__menu" class:navbar__menu--open={menuOpen} aria-hidden={!menuOpen} role="navigation" aria-label="Mobile menu">
      {#each menuLinks as link}
        <div class="navbar__item">
          <a href={link.href} class="navbar__link" tabindex={menuOpen ? 0 : -1}>{link.label}</a>
        </div>
      {/each}
    </div>
  </div>
</nav>
