// packages/rizzo-css/scaffold/react/Radio.tsx
import type { InputHTMLAttributes } from 'react';

export interface RadioProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> {
  /** Selected value for the radio group. Use the same name for all radios in the group. */
  group?: string;
  ariaDescribedby?: string;
  ariaLabel?: string;
  className?: string;
}

export function Radio({
  id,
  name,
  value = '',
  required = false,
  disabled = false,
  className = '',
  ariaDescribedby,
  ariaLabel,
  ...rest
}: RadioProps) {
  return (
    <input
      type="radio"
      id={id}
      name={name}
      value={value}
      required={required}
      disabled={disabled}
      className={className}
      aria-describedby={ariaDescribedby}
      aria-label={ariaLabel}
      {...rest}
    />
  );
}

export default Radio;

// packages/rizzo-css/scaffold/svelte-app/src/lib/rizzo/Radio.svelte
<script lang="ts">
  interface Props {
    id?: string;
    name?: string;
    value?: string;
    /** Bind the selected value for the radio group. Use the same bound variable for all radios in the group. */
    group?: string;
    required?: boolean;
    disabled?: boolean;
    class?: string;
    ariaDescribedby?: string;
    ariaLabel?: string;
  }
  let {
    id,
    name,
    value = '',
    group = $bindable(undefined as string | undefined),
    required = false,
    disabled = false,
    class: className = '',
    ariaDescribedby,
    ariaLabel,
  }: Props = $props();
</script>

<input
  type="radio"
  {id}
  {name}
  {value}
  bind:group={group}
  {required}
  {disabled}
  class={className}
  aria-describedby={ariaDescribedby}
  aria-label={ariaLabel}
/>
