// packages/rizzo-css/scaffold/svelte/Alert.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: 'success' | 'error' | 'warning' | 'info';
    dismissible?: boolean;
    autoDismiss?: number;
    class?: string;
    id?: string;
    onDismiss?: () => void;
    children?: Snippet;
  }
  let {
    variant = 'info',
    dismissible = false,
    autoDismiss = 0,
    class: className = '',
    id,
    onDismiss,
    children,
  }: Props = $props();

  let visible = $state(true);
  const alertId = $derived(id ?? `alert-${Math.random().toString(36).slice(2, 11)}`);
  const classes = $derived(['alert', `alert--${variant}`, className].filter(Boolean).join(' ').trim());

  const ariaLabels: Record<string, string> = {
    success: 'Success message',
    error: 'Error message',
    warning: 'Warning message',
    info: 'Information message',
  };

  let autoDismissTimeout: ReturnType<typeof setTimeout> | null = null;

  function dismiss() {
    visible = false;
    if (autoDismissTimeout) clearTimeout(autoDismissTimeout);
    onDismiss?.();
  }

  onMount(() => {
    if (autoDismiss > 0) {
      autoDismissTimeout = setTimeout(dismiss, autoDismiss);
    }
    return () => {
      if (autoDismissTimeout) clearTimeout(autoDismissTimeout);
    };
  });
</script>

{#if visible}
  <div
    class={classes}
    id={alertId}
    role="alert"
    aria-live="polite"
    aria-atomic="true"
    aria-label={ariaLabels[variant]}
  >
    <div class="alert__content">
      {@render children?.()}
    </div>
    {#if dismissible}
      <button
        type="button"
        class="alert__close"
        aria-label="Dismiss alert"
        aria-controls={alertId}
        onclick={dismiss}
        onkeydown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            dismiss();
          }
        }}
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
          <title>Dismiss</title>
          <path d="M18 6L6 18M6 6l12 12" />
        </svg>
      </button>
    {/if}
  </div>
{/if}

// src/components/react/Alert.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { useEffect, useRef, useState } from 'react';

export type AlertVariant = 'success' | 'error' | 'warning' | 'info';

export interface AlertProps extends Omit<HTMLAttributes<HTMLDivElement>, 'onDismiss'> {
  variant?: AlertVariant;
  dismissible?: boolean;
  autoDismiss?: number;
  onDismiss?: () => void;
  children?: ReactNode;
  className?: string;
  id?: string;
}

const ARIA_LABELS: Record<AlertVariant, string> = {
  success: 'Success message',
  error: 'Error message',
  warning: 'Warning message',
  info: 'Information message',
};

export function Alert({
  variant = 'info',
  dismissible = false,
  autoDismiss = 0,
  onDismiss,
  className = '',
  id: idProp,
  children,
  ...rest
}: AlertProps) {
  const [visible, setVisible] = useState(true);
  const id = idProp ?? `alert-${Math.random().toString(36).slice(2, 11)}`;
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const dismiss = () => {
    setVisible(false);
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    onDismiss?.();
  };

  useEffect(() => {
    if (autoDismiss > 0) {
      timeoutRef.current = setTimeout(dismiss, autoDismiss);
    }
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, [autoDismiss]);

  if (!visible) return null;

  const classes = ['alert', `alert--${variant}`, className].filter(Boolean).join(' ').trim();

  return (
    <div
      className={classes}
      id={id}
      role="alert"
      aria-live="polite"
      aria-atomic="true"
      aria-label={ARIA_LABELS[variant]}
      {...rest}
    >
      <div className="alert__content">{children}</div>
      {dismissible && (
        <button
          type="button"
          className="alert__close"
          aria-label="Dismiss alert"
          aria-controls={id}
          onClick={dismiss}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              dismiss();
            }
          }}
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
      )}
    </div>
  );
}

export default Alert;
