// src/components/svelte/AspectRatio.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    ratio?: number;
    class?: string;
    children?: Snippet;
  }

  let { ratio = 16 / 9, class: className = '', children }: Props = $props();
  const paddingPercent = $derived((1 / ratio) * 100);
</script>

<div
  class="aspect-ratio {className}"
  style="--aspect-ratio: {ratio}; --aspect-ratio-padding: {paddingPercent}%;"
>
  <div class="aspect-ratio__inner">
    {@render children?.()}
  </div>
</div>

// src/components/react/AspectRatio.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface AspectRatioProps extends HTMLAttributes<HTMLDivElement> {
  ratio?: number;
  children?: ReactNode;
  className?: string;
}

export function AspectRatio({
  ratio = 16 / 9,
  className = '',
  children,
  style,
  ...rest
}: AspectRatioProps) {
  const paddingPercent = (1 / ratio) * 100;
  return (
    <div
      className={`aspect-ratio ${className}`.trim()}
      style={{
        ['--aspect-ratio' as string]: ratio,
        ['--aspect-ratio-padding' as string]: `${paddingPercent}%`,
        ...(style as React.CSSProperties),
      }}
      {...rest}
    >
      <div className="aspect-ratio__inner">{children}</div>
    </div>
  );
}

export default AspectRatio;
