// src/components/svelte/ButtonGroup.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    orientation?: 'horizontal' | 'vertical';
    class?: string;
    children?: Snippet;
  }

  let { orientation = 'horizontal', class: className = '', children }: Props = $props();
  const orientationClass = $derived(orientation === 'vertical' ? 'button-group--vertical' : '');
</script>

<div class="button-group {orientationClass} {className}" role="group">
  {@render children?.()}
</div>

// src/components/react/ButtonGroup.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface ButtonGroupProps extends HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical';
  children?: ReactNode;
  className?: string;
}

export function ButtonGroup({
  orientation = 'horizontal',
  className = '',
  children,
  ...rest
}: ButtonGroupProps) {
  const orientationClass = orientation === 'vertical' ? 'button-group--vertical' : '';
  const classes = ['button-group', orientationClass, className].filter(Boolean).join(' ').trim();
  return (
    <div className={classes} role="group" {...rest}>
      {children}
    </div>
  );
}

export default ButtonGroup;
