// src/components/svelte/Card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  type Variant = 'default' | 'elevated' | 'outlined' | 'filled';
  interface Props {
    variant?: Variant;
    class?: string;
    children?: Snippet;
  }
  let { variant = 'default', class: className = '', children }: Props = $props();
  const variantClass = $derived(variant !== 'default' ? `card--${variant}` : '');
  const classes = $derived(['card', variantClass, className].filter(Boolean).join(' ').trim());
</script>

<div class={classes}>
  {@render children?.()}
</div>

// src/components/react/Card.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export type CardVariant = 'default' | 'elevated' | 'outlined' | 'filled';

export interface CardProps extends HTMLAttributes<HTMLDivElement> {
  variant?: CardVariant;
  children?: ReactNode;
  className?: string;
}

export function Card({
  variant = 'default',
  className = '',
  children,
  ...rest
}: CardProps) {
  const variantClass = variant !== 'default' ? `card--${variant}` : '';
  const classes = ['card', variantClass, className].filter(Boolean).join(' ').trim();
  return (
    <div className={classes} {...rest}>
      {children}
    </div>
  );
}

export default Card;
