// packages/rizzo-css/scaffold/svelte/Dashboard.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    /** Aria-label for the sidebar (e.g. "Dashboard navigation") */
    sidebarLabel?: string;
    /** Optional class for the root wrapper */
    class?: string;
    /** Main content */
    children: Snippet;
    /** Optional sidebar content; if not provided, default nav links are shown */
    sidebar?: Snippet;
  }
  let {
    sidebarLabel = 'Dashboard navigation',
    class: className = '',
    children,
    sidebar,
  }: Props = $props();

  const classes = $derived(['dashboard', className].filter(Boolean).join(' ').trim());
</script>

<div class={classes}>
  <aside class="dashboard__sidebar" aria-label={sidebarLabel}>
    {#if sidebar}
      {@render sidebar()}
    {:else}
      <nav class="dashboard__nav">
        <a href="/" class="dashboard__nav-link dashboard__nav-link--active" aria-current="page">Dashboard</a>
        <a href="/" class="dashboard__nav-link">Items</a>
        <a href="/" class="dashboard__nav-link">Settings</a>
      </nav>
    {/if}
  </aside>
  <main id="main-content" class="dashboard__main">
    {@render children()}
  </main>
</div>

<style>
  .dashboard {
    display: flex;
    min-height: 100vh;
  }
  .dashboard__sidebar {
    width: 16rem;
    flex-shrink: 0;
    border-right: 1px solid var(--border);
    padding: var(--spacing-4);
    background: var(--background-alt);
  }
  .dashboard__nav {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-1);
  }
  .dashboard__nav-link {
    display: block;
    padding: var(--spacing-2) var(--spacing-3);
    border-radius: var(--radius-md);
    color: var(--text);
    text-decoration: none;
  }
  .dashboard__nav-link:hover {
    background: var(--background);
  }
  .dashboard__nav-link--active {
    background: var(--accent);
    color: var(--accent-text);
  }
  .dashboard__main {
    flex: 1;
    padding: var(--spacing-6);
    overflow: auto;
  }
  @media (max-width: 768px) {
    .dashboard {
      flex-direction: column;
    }
    .dashboard__sidebar {
      width: 100%;
      border-right: none;
      border-bottom: 1px solid var(--border);
    }
  }
</style>

// src/components/react/Dashboard.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface DashboardProps extends HTMLAttributes<HTMLDivElement> {
  /** Sidebar content (nav with dashboard__nav and dashboard__nav-link). If omitted, default Dashboard/Items/Settings links are shown. */
  sidebar?: ReactNode;
  children?: ReactNode;
  className?: string;
  /** Aria-label for the sidebar (default: "Dashboard navigation") */
  sidebarLabel?: string;
}

export function Dashboard({
  sidebar,
  children,
  className = '',
  sidebarLabel = 'Dashboard navigation',
  ...rest
}: DashboardProps) {
  return (
    <div className={`dashboard ${className}`.trim()} data-dashboard {...rest}>
      <aside className="dashboard__sidebar" aria-label={sidebarLabel}>
        {sidebar ?? (
          <nav className="dashboard__nav">
            <a href="/" className="dashboard__nav-link dashboard__nav-link--active" aria-current="page">Dashboard</a>
            <a href="/" className="dashboard__nav-link">Items</a>
            <a href="/" className="dashboard__nav-link">Settings</a>
          </nav>
        )}
      </aside>
      <main id="main-content" className="dashboard__main">{children}</main>
    </div>
  );
}

export default Dashboard;
