// packages/rizzo-css/scaffold/svelte/Direction.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    dir?: 'ltr' | 'rtl';
    class?: string;
    children?: Snippet;
  }

  let { dir = 'ltr', class: className = '', children }: Props = $props();

  const dirClass = $derived(dir === 'rtl' ? 'direction--rtl' : 'direction--ltr');
</script>

<div class="direction {dirClass} {className}" {dir}>
  {@render children?.()}
</div>

// src/components/react/Direction.tsx
import type { HTMLAttributes } from 'react';

export interface DirectionProps extends HTMLAttributes<HTMLDivElement> {
  dir?: 'ltr' | 'rtl';
  className?: string;
}

export function Direction({
  dir = 'ltr',
  className = '',
  children,
  ...rest
}: DirectionProps) {
  const dirClass = dir === 'rtl' ? 'direction--rtl' : 'direction--ltr';
  return (
    <div className={`direction ${dirClass} ${className}`.trim()} dir={dir} {...rest}>
      {children}
    </div>
  );
}

export default Direction;
