// src/components/svelte/ResizablePane.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    defaultSize?: number;
    class?: string;
    children?: Snippet;
  }

  let { defaultSize = 50, class: className = '', children }: Props = $props();
  const size = Math.min(100, Math.max(0, defaultSize));
</script>

<div class="resizable__pane {className}" data-resizable-pane style="flex: 1 1 {size}%">
  {@render children?.()}
</div>

// src/components/react/ResizablePane.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface ResizablePaneProps extends HTMLAttributes<HTMLDivElement> {
  defaultSize?: number;
  children?: ReactNode;
  className?: string;
}

export function ResizablePane({
  defaultSize = 50,
  className = '',
  children,
  style,
  ...rest
}: ResizablePaneProps) {
  const size = Math.min(100, Math.max(0, defaultSize));
  return (
    <div
      className={`resizable__pane ${className}`.trim()}
      data-resizable-pane
      style={{ flex: `1 1 ${size}%`, ...(style as object) }}
      {...rest}
    >
      {children}
    </div>
  );
}

export default ResizablePane;
