// packages/rizzo-css/scaffold/svelte/Settings.svelte
<script lang="ts">
  interface Props {
    open?: boolean;
  }
  let { open: openProp }: Props = $props();
  let openInternal = $state(false);
  const open = $derived(openProp !== undefined ? openProp : openInternal);

  $effect(() => {
    (window as unknown as { openSettings?: () => void }).openSettings = () => {
      openInternal = true;
    };
    return () => {
      if ((window as unknown as { openSettings?: () => void }).openSettings) {
        delete (window as unknown as { openSettings?: () => void }).openSettings;
      }
    };
  });

  $effect(() => {
    if (!open) return;
    const onEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') openInternal = false;
    };
    document.addEventListener('keydown', onEscape);
    return () => document.removeEventListener('keydown', onEscape);
  });

  function close() {
    openInternal = false;
  }
</script>

<div class="settings" data-settings aria-hidden={!open}>
  <div class="settings__overlay" data-settings-overlay aria-hidden={!open} onclick={close}></div>
  <div
    class="settings__panel"
    role="dialog"
    aria-modal="true"
    aria-labelledby="settings-title"
    aria-hidden={!open}
    data-open={open ? 'true' : undefined}
  >
    <div class="settings__header">
      <h2 id="settings-title" class="settings__title">Settings</h2>
      <button type="button" class="settings__close" data-settings-close aria-label="Close settings" onclick={close}>×</button>
    </div>
    <div class="settings__content">
      <p>Theme, font size, and accessibility options. Wire to your state or use <code>window.openSettings</code>.</p>
    </div>
  </div>
</div>

// src/components/react/Settings.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { useEffect } from 'react';

export interface SettingsProps extends HTMLAttributes<HTMLDivElement> {
  id?: string;
  title?: string;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  children?: ReactNode;
  className?: string;
}

export function Settings({
  id: idProp,
  title = 'Settings',
  open = false,
  onOpenChange,
  children,
  className = '',
  ...rest
}: SettingsProps) {
  const id = idProp ?? `settings-${Math.random().toString(36).slice(2, 9)}`;

  useEffect(() => {
    if (!open) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onOpenChange?.(false);
      }
    };
    document.addEventListener('keydown', handleKey);
    return () => document.removeEventListener('keydown', handleKey);
  }, [open, onOpenChange]);

  return (
    <div
      className={`settings ${open ? 'settings--open' : ''} ${className}`.trim()}
      id={id}
      data-settings
      role="dialog"
      aria-modal="true"
      aria-labelledby={`${id}-title`}
      aria-hidden={!open}
      hidden={!open}
      {...rest}
    >
      <div className="settings__backdrop" onClick={() => onOpenChange?.(false)} aria-hidden="true" />
      <div className="settings__panel">
        <div className="settings__header">
          <h2 id={`${id}-title`} className="settings__title">{title}</h2>
          <button type="button" className="settings__close" aria-label="Close settings" onClick={() => onOpenChange?.(false)}>×</button>
        </div>
        <div className="settings__body">{children}</div>
      </div>
    </div>
  );
}

export default Settings;
