// src/components/svelte/Settings.svelte
<script lang="ts">
  import ThemeSwitcher from './ThemeSwitcher.svelte';
  import FontSwitcher from './FontSwitcher.svelte';
  import SoundEffects from './SoundEffects.svelte';
  import Close from './icons/Close.svelte';

  interface Props {
    open?: boolean;
  }
  let { open: openProp }: Props = $props();
  let openInternal = $state(false);
  let closing = $state(false);
  const open = $derived(openProp !== undefined ? openProp : openInternal);

  const isBrowser = typeof window !== 'undefined' && typeof localStorage?.getItem === 'function';
  let fontSizeLabel = $state('100%');
  let fontSizeSlider = $state(1);
  let reducedMotion = $state(isBrowser && localStorage.getItem('reducedMotion') === 'true');
  let highContrast = $state(isBrowser && localStorage.getItem('highContrast') === 'true');
  let scrollbarStyle = $state((isBrowser ? localStorage.getItem('scrollbarStyle') || 'thin' : 'thin') as 'thin' | 'thick' | 'hidden');

  function applyFontSize(scale: number) {
    if (typeof document === 'undefined') return;
    document.documentElement.style.setProperty('--font-size-scale', String(scale));
    localStorage?.setItem('fontSizeScale', String(scale));
    fontSizeLabel = `${Math.round(scale * 100)}%`;
  }

  let opening = $state(false);
  /** Panel shows open state only after first frame when opening (so slide-in animation runs). */
  const panelDataOpen = $derived(open && !closing && !opening);

  $effect(() => {
    if (typeof window === 'undefined') return;
    (window as unknown as { openSettings?: () => void }).openSettings = () => {
      openInternal = true;
      opening = true;
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          opening = false;
        });
      });
    };
    return () => {
      if ((window as unknown as { openSettings?: () => void }).openSettings) {
        delete (window as unknown as { openSettings?: () => void }).openSettings;
      }
    };
  });

  $effect(() => {
    if (typeof document === 'undefined' || !open) return;
    const onEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close();
    };
    document.addEventListener('keydown', onEscape);
    return () => document.removeEventListener('keydown', onEscape);
  });

  $effect(() => {
    if (open && typeof document !== 'undefined') {
      const saved = localStorage?.getItem('fontSizeScale');
      const scale = saved ? parseFloat(saved) : 1;
      fontSizeSlider = scale;
      fontSizeLabel = `${Math.round(scale * 100)}%`;
      reducedMotion = localStorage?.getItem('reducedMotion') === 'true';
      highContrast = localStorage?.getItem('highContrast') === 'true';
      scrollbarStyle = (localStorage?.getItem('scrollbarStyle') || 'thin') as 'thin' | 'thick' | 'hidden';
    }
  });

  function close() {
    const prefersReducedMotion = typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const reducedMotionClass = typeof document !== 'undefined' && document.documentElement.classList.contains('reduced-motion');
    const duration = (prefersReducedMotion || reducedMotionClass) ? 0 : 300;
    if (duration === 0) {
      openInternal = false;
      return;
    }
    closing = true;
    setTimeout(() => {
      openInternal = false;
      closing = false;
    }, duration);
  }

  function onFontSizeInput(e: Event) {
    const target = e.target as HTMLInputElement;
    const scale = parseFloat(target.value);
    fontSizeSlider = scale;
    applyFontSize(scale);
  }

  function onReducedMotionChange(e: Event) {
    const checked = (e.target as HTMLInputElement).checked;
    reducedMotion = checked;
    localStorage?.setItem('reducedMotion', checked ? 'true' : '');
    document.documentElement.classList.toggle('reduced-motion', checked);
  }

  function onHighContrastChange(e: Event) {
    const checked = (e.target as HTMLInputElement).checked;
    highContrast = checked;
    localStorage?.setItem('highContrast', checked ? 'true' : '');
    document.documentElement.classList.toggle('high-contrast', checked);
  }

  function onScrollbarStyleChange(e: Event) {
    const value = (e.target as HTMLInputElement).value as 'thin' | 'thick' | 'hidden';
    scrollbarStyle = value;
    localStorage?.setItem('scrollbarStyle', value);
    document.documentElement.classList.remove('scrollbar-thick', 'scrollbar-hidden', 'hide-scrollbars');
    if (value === 'thick') document.documentElement.classList.add('scrollbar-thick');
    else if (value === 'hidden') document.documentElement.classList.add('scrollbar-hidden', 'hide-scrollbars');
  }
</script>

<div class="settings" data-settings aria-hidden={!open}>
  <div class="settings__overlay" data-settings-overlay aria-hidden={!open} onclick={close}></div>
  <div
    class="settings__panel"
    role="dialog"
    aria-modal="true"
    aria-labelledby="settings-title"
    aria-hidden={!open}
    data-open={panelDataOpen ? 'true' : undefined}
  >
    <div class="settings__header">
      <h2 id="settings-title" class="settings__title">Settings</h2>
      <button type="button" class="settings__close" data-settings-close aria-label="Close settings" title="Close settings" onclick={close}>
        <Close width={20} height={20} />
      </button>
    </div>
    <div class="settings__content" tabindex="-1" aria-label="Settings options">
      <section class="settings__section">
        <h3 class="settings__section-title">Theme</h3>
        <div class="settings__control">
          <ThemeSwitcher idPrefix="settings" />
        </div>
      </section>
      <section class="settings__section">
        <h3 class="settings__section-title">Font Size</h3>
        <div class="settings__control">
          <label for="font-size-slider" class="settings__label">
            <span class="settings__label-text">Adjust text size</span>
            <span class="settings__label-value">{fontSizeLabel}</span>
          </label>
          <input
            type="range"
            id="font-size-slider"
            class="settings__slider"
            min="0.75"
            max="1.5"
            step="0.05"
            value={fontSizeSlider}
            oninput={onFontSizeInput}
            aria-label="Font size"
            data-font-size-slider
            style="--slider-progress: {((fontSizeSlider - 0.75) / 0.75) * 100}%;"
          />
          <div class="settings__slider-labels"><span>Small</span><span>Default</span><span>Large</span></div>
        </div>
      </section>
      <section class="settings__section">
        <h3 class="settings__section-title">Font</h3>
        <div class="settings__control">
          <FontSwitcher idPrefix="settings" />
          <p class="settings__help-text">Body text and code blocks use the selected pair.</p>
        </div>
      </section>
      <section class="settings__section">
        <h3 class="settings__section-title">Sound</h3>
        <div class="settings__control">
          <SoundEffects showHelp={true} />
        </div>
      </section>
      <section class="settings__section">
        <h3 class="settings__section-title">Accessibility</h3>
        <div class="settings__control">
          <label class="settings__checkbox-label">
            <input type="checkbox" class="settings__checkbox" data-reduced-motion aria-label="Reduce motion" checked={reducedMotion} onchange={onReducedMotionChange} />
            <span>Reduce motion</span>
          </label>
          <p class="settings__help-text">Minimize animations and transitions</p>
        </div>
        <div class="settings__control">
          <label class="settings__checkbox-label">
            <input type="checkbox" class="settings__checkbox" aria-label="High contrast" checked={highContrast} onchange={onHighContrastChange} />
            <span>High contrast</span>
          </label>
          <p class="settings__help-text">Increase contrast for better visibility</p>
        </div>
        <div class="settings__control">
          <div class="settings__label"><span class="settings__label-text">Scrollbar style</span></div>
          <div class="settings__radio-group" role="radiogroup" aria-label="Scrollbar style">
            <label class="settings__radio-label">
              <input type="radio" name="scrollbar-style" value="thin" class="settings__radio" aria-label="Thin scrollbar" checked={scrollbarStyle === 'thin'} onchange={onScrollbarStyleChange} />
              <span>Thin</span>
            </label>
            <label class="settings__radio-label">
              <input type="radio" name="scrollbar-style" value="thick" class="settings__radio" aria-label="Thick scrollbar" checked={scrollbarStyle === 'thick'} onchange={onScrollbarStyleChange} />
              <span>Thick</span>
            </label>
            <label class="settings__radio-label">
              <input type="radio" name="scrollbar-style" value="hidden" class="settings__radio" aria-label="Hidden scrollbars" checked={scrollbarStyle === 'hidden'} onchange={onScrollbarStyleChange} />
              <span>Hidden</span>
            </label>
          </div>
          <p class="settings__help-text">Choose your preferred scrollbar appearance</p>
        </div>
      </section>
    </div>
  </div>
</div>

// src/components/react/Settings.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { useCallback, useEffect, useState, useRef } from 'react';

export interface SettingsProps extends HTMLAttributes<HTMLDivElement> {
  id?: string;
  title?: string;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  children?: ReactNode;
  className?: string;
}

const CLOSE_DURATION = 300;

function getReduceMotion(): boolean {
  if (typeof window === 'undefined') return true;
  return (
    window.matchMedia('(prefers-reduced-motion: reduce)').matches ||
    document.documentElement.classList.contains('reduced-motion')
  );
}

export function Settings({
  id: idProp,
  title = 'Settings',
  open = false,
  onOpenChange,
  children,
  className = '',
  ...rest
}: SettingsProps) {
  const id = idProp ?? `settings-${Math.random().toString(36).slice(2, 9)}`;
  const [closing, setClosing] = useState(false);
  const [opening, setOpening] = useState(false);
  const prevOpen = useRef(open);

  /** Keep panel visible while close animation runs; hide only when not open and not closing. */
  const visible = open || closing;
  /** Panel data-open: show slide-in only after first frame when opening; remove for slide-out when closing. */
  const panelDataOpen = open && !closing && !opening;

  useEffect(() => {
    if (open && !prevOpen.current) {
      setOpening(true);
      const t = requestAnimationFrame(() => {
        requestAnimationFrame(() => setOpening(false));
      });
      return () => cancelAnimationFrame(t);
    }
    prevOpen.current = open;
  }, [open]);

  const handleClose = useCallback(() => {
    const duration = getReduceMotion() ? 0 : CLOSE_DURATION;
    if (duration === 0) {
      onOpenChange?.(false);
      return;
    }
    setClosing(true);
    const t = setTimeout(() => {
      setClosing(false);
      onOpenChange?.(false);
    }, duration);
    return () => clearTimeout(t);
  }, [onOpenChange]);

  useEffect(() => {
    if (!open) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        handleClose();
      }
    };
    document.addEventListener('keydown', handleKey);
    return () => document.removeEventListener('keydown', handleKey);
  }, [open, handleClose]);

  return (
    <div
      className={`settings ${className}`.trim()}
      id={id}
      data-settings
      aria-hidden={!visible}
      {...rest}
    >
      <div
        className="settings__overlay"
        data-settings-overlay
        aria-hidden="true"
        onClick={handleClose}
      />
      <div
        className="settings__panel"
        role="dialog"
        aria-modal="true"
        aria-labelledby={`${id}-title`}
        aria-hidden={!visible}
        data-open={panelDataOpen ? 'true' : undefined}
      >
        <div className="settings__header">
          <h2 id={`${id}-title`} className="settings__title">
            {title}
          </h2>
          <button
            type="button"
            className="settings__close"
            data-settings-close
            aria-label="Close settings"
            title="Close settings"
            onClick={handleClose}
          >
            ×
          </button>
        </div>
        <div className="settings__content" tabIndex={-1} aria-label="Settings options">
          {children}
        </div>
      </div>
    </div>
  );
}

export default Settings;
