// packages/rizzo-css/scaffold/svelte/Divider.svelte
<script lang="ts">
  interface Props {
    orientation?: 'horizontal' | 'vertical';
    label?: string;
    class?: string;
  }
  let { orientation = 'horizontal', label, class: className = '' }: Props = $props();
  const orientationClass = `divider--${orientation}`;
  const hasLabel = typeof label === 'string' && label.trim().length > 0;
  const labelClass = hasLabel ? 'divider--labeled' : '';
  const classes = ['divider', orientationClass, labelClass, className].filter(Boolean).join(' ').trim();
  const labelText = label?.trim() ?? '';
</script>

<div
  class={classes}
  role="separator"
  aria-orientation={orientation}
  aria-label={labelText || undefined}
>
  {#if hasLabel && orientation === 'horizontal'}
    <span class="divider__line" aria-hidden="true" />
    <span class="divider__label">{labelText}</span>
    <span class="divider__line" aria-hidden="true" />
  {:else}
    <span class="divider__line" aria-hidden="true" />
  {/if}
</div>

// packages/rizzo-css/scaffold/vue/Divider.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    orientation?: 'horizontal' | 'vertical';
    label?: string;
    class?: string;
  }>(),
  { orientation: 'horizontal', class: '' }
);
</script>

<template>
  <div
    :class="['divider', `divider--${orientation}`, label ? 'divider--labeled' : '', $props.class].filter(Boolean).join(' ')"
    role="separator"
    :aria-orientation="orientation"
    :aria-label="label?.trim() || undefined"
  >
    <span v-if="label && orientation === 'horizontal'" class="divider__line" aria-hidden="true" />
    <span v-if="label && orientation === 'horizontal'" class="divider__label">{{ label }}</span>
    <span class="divider__line" aria-hidden="true" />
  </div>
</template>
