// src/components/svelte/FormGroup.svelte
<script lang="ts">
  interface Props {
    label?: string;
    labelFor?: string;
    required?: boolean;
    help?: string;
    error?: string;
    success?: string;
    class?: string;
  }
  let {
    label,
    labelFor,
    required = false,
    help,
    error,
    success,
    class: className = '',
  }: Props = $props();

  const errorId = $derived(labelFor && error ? `${labelFor}-error` : undefined);
  const helpId = $derived(labelFor && help ? `${labelFor}-help` : undefined);
</script>

<div class="form-group {className}">
  {#if label}
    <label for={labelFor} class="form-group__label {required ? 'required' : ''}">
      {label}
    </label>
  {/if}
  <slot />
  {#if help}
    <span id={helpId} class="form-group__help">{help}</span>
  {/if}
  {#if error}
    <span id={errorId} class="form-error" role="alert">{error}</span>
  {/if}
  {#if success}
    <span class="form-success" role="status">{success}</span>
  {/if}
</div>

// packages/rizzo-css/scaffold/vue/FormGroup.vue
<script setup lang="ts">
defineProps({
  label: { type: String, default: undefined },
  labelFor: { type: String, default: undefined },
  required: { type: Boolean, default: false },
  help: { type: String, default: undefined },
  error: { type: String, default: undefined },
  success: { type: String, default: undefined },
  class: { type: String, default: '' },
});
</script>

<template>
  <div :class="['form-group', $props.class].filter(Boolean).join(' ')">
    <label
      v-if="label && labelFor"
      :for="labelFor"
      :class="['form-group__label', required ? 'required' : ''].filter(Boolean).join(' ')"
    >
      {{ label }}
    </label>
    <span
      v-else-if="label"
      :class="['form-group__label', required ? 'required' : ''].filter(Boolean).join(' ')"
    >
      {{ label }}
    </span>
    <slot />
    <span v-if="help" :id="labelFor && help ? `${labelFor}-help` : undefined" class="form-group__help">
      {{ help }}
    </span>
    <span
      v-if="error"
      :id="labelFor && error ? `${labelFor}-error` : undefined"
      class="form-error"
      role="alert"
    >
      {{ error }}
    </span>
    <span v-if="success" class="form-success" role="status">{{ success }}</span>
  </div>
</template>
