// src/components/react/Badge.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export type BadgeVariant = 'primary' | 'success' | 'warning' | 'error' | 'info';
export type BadgeSize = 'sm' | 'md' | 'lg';

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant;
  size?: BadgeSize;
  pill?: boolean;
  children?: ReactNode;
  className?: string;
}

export function Badge({
  variant = 'primary',
  size = 'md',
  pill = false,
  className = '',
  children,
  ...rest
}: BadgeProps) {
  const classes = [
    'badge',
    `badge--${variant}`,
    `badge--${size}`,
    pill ? 'badge--pill' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ')
    .trim();
  return (
    <span className={classes} {...rest}>
      {children}
    </span>
  );
}

export default Badge;

// packages/rizzo-css/scaffold/svelte/Badge.svelte
<script lang="ts">
  type Variant = 'primary' | 'success' | 'warning' | 'error' | 'info';
  type Size = 'sm' | 'md' | 'lg';
  interface Props {
    variant?: Variant;
    size?: Size;
    pill?: boolean;
    class?: string;
  }
  let {
    variant = 'primary',
    size = 'md',
    pill = false,
    class: className = '',
  }: Props = $props();

  const classes = [
    'badge',
    `badge--${variant}`,
    `badge--${size}`,
    pill ? 'badge--pill' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ')
    .trim();
</script>

<span class={classes}>
  <slot />
</span>
