// src/components/vue/Button.vue
<script setup lang="ts">
type Variant = 'default' | 'primary' | 'success' | 'warning' | 'error' | 'info' | 'outline';

withDefaults(
  defineProps<{
    variant?: Variant;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    class?: string;
  }>(),
  { variant: 'default', disabled: false, type: 'button', class: '' }
);
</script>

<template>
  <button
    :type="type"
    :disabled="disabled"
    :class="['btn', variant !== 'default' ? `btn-${variant}` : '', $props.class].filter(Boolean).join(' ')"
  >
    <slot />
  </button>
</template>

// packages/rizzo-css/scaffold/svelte/Button.svelte
<script lang="ts">
  type Variant = 'default' | 'primary' | 'success' | 'warning' | 'error' | 'info' | 'outline';
  interface Props {
    variant?: Variant;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    class?: string;
  }
  let {
    variant = 'default',
    disabled = false,
    type = 'button',
    class: className = '',
    ...rest
  }: Props = $props();

  const variantClass = variant === 'default' ? '' : `btn-${variant}`;
  const classes = ['btn', variantClass, className].filter(Boolean).join(' ');
</script>

<button {type} {disabled} class={classes} {...rest}>
  <slot />
</button>
