// packages/rizzo-css/scaffold/vue/Card.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    variant?: 'default' | 'outlined' | 'elevated';
    class?: string;
  }>(),
  { variant: 'default', class: '' }
);
</script>

<template>
  <div
    :class="[
      'card',
      variant !== 'default' ? `card--${variant}` : '',
      $props.class,
    ].filter(Boolean).join(' ')"
  >
    <slot />
  </div>
</template>

// packages/rizzo-css/scaffold/svelte/Card.svelte
<script lang="ts">
  type Variant = 'default' | 'elevated' | 'outlined' | 'filled';
  interface Props {
    variant?: Variant;
    class?: string;
  }
  let { variant = 'default', class: className = '' }: Props = $props();
  const variantClass = variant !== 'default' ? `card--${variant}` : '';
  const classes = ['card', variantClass, className].filter(Boolean).join(' ').trim();
</script>

<div class={classes}>
  <slot />
</div>
