// src/components/react/ContextMenu.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { useState, useRef, useEffect } from 'react';

export interface ContextMenuProps extends HTMLAttributes<HTMLDivElement> {
  id?: string;
  children?: ReactNode;
  trigger?: ReactNode;
  className?: string;
}

export function ContextMenu({
  id: idProp,
  children,
  trigger,
  className = '',
  ...rest
}: ContextMenuProps) {
  const id = idProp ?? `context-menu-${Math.random().toString(36).slice(2, 9)}`;
  const [open, setOpen] = useState(false);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const contentRef = useRef<HTMLDivElement>(null);

  const handleContextMenu = (e: React.MouseEvent) => {
    e.preventDefault();
    setPosition({ x: e.clientX, y: e.clientY });
    setOpen(true);
    requestAnimationFrame(() => document.addEventListener('click', closeMenu));
  };

  const closeMenu = () => {
    setOpen(false);
    document.removeEventListener('click', closeMenu);
  };

  const handleKeydown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') closeMenu();
  };

  useEffect(() => {
    if (open && contentRef.current) {
      contentRef.current.style.left = `${position.x}px`;
      contentRef.current.style.top = `${position.y}px`;
    }
  }, [open, position]);

  return (
    <div className={`context-menu ${className}`.trim()} data-context-menu id={id} {...rest}>
      <div data-context-menu-trigger onContextMenu={handleContextMenu}>
        {trigger}
      </div>
      <div
        ref={contentRef}
        className={`context-menu__content ${open ? 'context-menu__content--open' : ''}`.trim()}
        role="menu"
        aria-hidden={!open}
        hidden={!open}
        data-context-menu-content
        id={`${id}-content`}
        onKeyDown={handleKeydown}
      >
        {children}
      </div>
    </div>
  );
}

export default ContextMenu;

// packages/rizzo-css/scaffold/svelte/ContextMenu.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    id?: string;
    class?: string;
    children?: Snippet;
    trigger?: Snippet;
  }

  let { id: ctxId, class: className = '', children, trigger }: Props = $props();

  const id = $derived(ctxId ?? `context-menu-${Math.random().toString(36).slice(2, 9)}`);
  let open = $state(false);
  let x = $state(0);
  let y = $state(0);
  let contentEl: HTMLDivElement;

  function handleContextMenu(e: MouseEvent) {
    e.preventDefault();
    x = e.clientX;
    y = e.clientY;
    open = true;
    requestAnimationFrame(() => document.addEventListener('click', closeMenu));
  }

  function closeMenu() {
    open = false;
    document.removeEventListener('click', closeMenu);
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') closeMenu();
  }

  $effect(() => {
    if (open && contentEl) {
      contentEl.style.left = `${x}px`;
      contentEl.style.top = `${y}px`;
    }
  });
</script>

<div class="context-menu {className}" data-context-menu {id}>
  <div data-context-menu-trigger oncontextmenu={handleContextMenu}>
    {@render trigger?.()}
  </div>
  <div
    bind:this={contentEl}
    class="context-menu__content {open ? 'context-menu__content--open' : ''}"
    role="menu"
    aria-hidden={!open}
    hidden={!open}
    data-context-menu-content
    id="{id}-content"
    onkeydown={handleKeydown}
  >
    {@render children?.()}
  </div>
</div>
