// src/components/vue/Direction.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps({
  dir: { type: String, default: 'ltr' },
  class: { type: String, default: '' },
});

const dirClass = computed(() => (props.dir === 'rtl' ? 'direction--rtl' : 'direction--ltr'));
const rootClass = computed(() => ['direction', dirClass.value, props.class].filter(Boolean).join(' '));
</script>

<template>
  <div :class="rootClass" :dir="dir">
    <slot />
  </div>
</template>

// packages/rizzo-css/scaffold/svelte/Direction.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    dir?: 'ltr' | 'rtl';
    class?: string;
    children?: Snippet;
  }

  let { dir = 'ltr', class: className = '', children }: Props = $props();

  const dirClass = $derived(dir === 'rtl' ? 'direction--rtl' : 'direction--ltr');
</script>

<div class="direction {dirClass} {className}" {dir}>
  {@render children?.()}
</div>
