// packages/rizzo-css/scaffold/vue/Input.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    type?: string;
    id?: string;
    name?: string;
    modelValue?: string;
    placeholder?: string;
    required?: boolean;
    disabled?: boolean;
    readonly?: boolean;
    size?: 'sm' | 'md' | 'lg';
    error?: boolean;
    success?: boolean;
    class?: string;
    ariaDescribedby?: string;
    ariaInvalid?: boolean | 'true' | 'false';
  }>(),
  {
    type: 'text',
    modelValue: '',
    required: false,
    disabled: false,
    readonly: false,
    size: 'md',
    error: false,
    success: false,
    class: '',
  }
);

const emit = defineEmits<{ (e: 'update:modelValue', value: string): void }>();

const sizeClass = props.size !== 'md' ? `form-input--${props.size}` : '';
const errorClass = props.error ? 'form-input--error' : '';
const successClass = props.success ? 'form-input--success' : '';
const classes = ['form-input', sizeClass, errorClass, successClass, props.class]
  .filter(Boolean)
  .join(' ')
  .trim();
const invalid = props.error || props.ariaInvalid === true || props.ariaInvalid === 'true';
</script>

<template>
  <input
    :type="type"
    :id="id"
    :name="name"
    :value="modelValue"
    :placeholder="placeholder"
    :required="required"
    :disabled="disabled"
    :readonly="readonly"
    :class="classes"
    :aria-invalid="invalid ? 'true' : 'false'"
    :aria-describedby="ariaDescribedby"
    @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
  />
</template>

// packages/rizzo-css/scaffold/svelte/Input.svelte
<script lang="ts">
  interface Props {
    type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' | 'search' | 'date' | 'time' | 'datetime-local' | 'month' | 'week';
    id?: string;
    name?: string;
    value?: string;
    placeholder?: string;
    required?: boolean;
    disabled?: boolean;
    readonly?: boolean;
    autocomplete?: string;
    size?: 'sm' | 'md' | 'lg';
    error?: boolean;
    success?: boolean;
    class?: string;
    ariaDescribedby?: string;
    ariaInvalid?: boolean | 'true' | 'false';
  }
  let {
    type = 'text',
    id,
    name,
    value = $bindable(''),
    placeholder,
    required = false,
    disabled = false,
    readonly = false,
    autocomplete,
    size = 'md',
    error = false,
    success = false,
    class: className = '',
    ariaDescribedby,
    ariaInvalid,
  }: Props = $props();

  const sizeClass = size !== 'md' ? `form-input--${size}` : '';
  const errorClass = error ? 'form-input--error' : '';
  const successClass = success ? 'form-input--success' : '';
  const classes = ['form-input', sizeClass, errorClass, successClass, className].filter(Boolean).join(' ').trim();
  const invalid = error || ariaInvalid === true || ariaInvalid === 'true';
</script>

<input
  {type}
  {id}
  {name}
  bind:value
  {placeholder}
  {required}
  {disabled}
  {readonly}
  autocomplete={autocomplete}
  class={classes}
  aria-invalid={invalid ? 'true' : 'false'}
  aria-describedby={ariaDescribedby}
/>
